name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run lint:ci
      - run: |
          git_tag="$(git describe --tags)"

          # Sync version number to all package.json files
          npm run version $git_tag
          npm install
          npm run build
          npm publish --access public

          if [[ $git_tag == *"beta"* ]]; then
            tag=beta
          elif [[ $git_tag == *"alpha"* ]]; then
            tag=alpha
          else
            tag=latest
          fi

          npm publish --access public --tag $TAG \
            --workspace core \
            --workspace connect \
            --workspace platforms \
            --workspace platforms/evm/protocols \
            --workspace platforms/solana/protocols \
            --workspace platforms/cosmwasm/protocols \
            --workspace platforms/algorand/protocols \
            --workspace platforms/sui/protocols \
            --workspace platforms/aptos/protocols \
            --workspace sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
